# Copyright {.unnumbered .unlisted}

::: {.content-visible when-format="pdf"}
```{=latex}
\thispagestyle{empty}
\vspace*{\fill}
\begin{center}
\begin{minipage}{0.85\textwidth}
\centering

\textit{Modern Financial Modeling: Concepts and Applications for Actuaries and Other Financial Professionals}

\bigskip

Copyright \textcopyright{} 2026 Alec Loudenback and Yun-Tien Lee.

\medskip

Published by Alec Loudenback and Yun-Tien Lee.

\medskip

This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0), except where otherwise noted. To view a copy of this license, visit \url{https://creativecommons.org/licenses/by-nc-sa/4.0/}.

\medskip

The chapters on developing in Julia (\emph{Writing Julia}, \emph{Debugging Julia}, \emph{Sharing Julia}, and \emph{Optimizing Julia}) are licensed under the Creative Commons Attribution-ShareAlike 4.0 International License (CC BY-SA 4.0). To view a copy of this license, visit \url{https://creativecommons.org/licenses/by-sa/4.0/}.

\medskip

This is not a Milliman-sponsored project.

\bigskip

ISBN 978-1-257-97605-8

\medskip

First edition, 2026.

\medskip

Published online at \url{https://ModernFinancialModeling.com}.

\end{minipage}
\end{center}
\vspace*{\fill}
\clearpage
```
:::

::: {.content-visible when-format="html"}
*Modern Financial Modeling: Concepts and Applications for Actuaries and Other Financial Professionals*

Copyright &copy; 2026 Alec Loudenback and Yun-Tien Lee.

Published by Alec Loudenback and Yun-Tien Lee.

This work is licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/) (CC BY-NC-SA 4.0), except where otherwise noted.

The chapters on developing in Julia (*Writing Julia*, *Debugging Julia*, *Sharing Julia*, and *Optimizing Julia*) are licensed under the [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/) (CC BY-SA 4.0).

This is not a Milliman-sponsored project.

ISBN 978-1-257-97605-8

First edition, 2026.

Published online at [ModernFinancialModeling.com](https://ModernFinancialModeling.com).
:::

::: {.content-visible when-format="epub"}
*Modern Financial Modeling: Concepts and Applications for Actuaries and Other Financial Professionals*

Copyright &copy; 2026 Alec Loudenback and Yun-Tien Lee.

Published by Alec Loudenback and Yun-Tien Lee.

This work is licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/) (CC BY-NC-SA 4.0), except where otherwise noted.

The chapters on developing in Julia (*Writing Julia*, *Debugging Julia*, *Sharing Julia*, and *Optimizing Julia*) are licensed under the [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/) (CC BY-SA 4.0).

This is not a Milliman-sponsored project.

ISBN 978-1-257-97605-8

First edition, 2026.

Published online at [ModernFinancialModeling.com](https://ModernFinancialModeling.com).
:::
