# Elements of Financial Modeling

> "Truth ... is much too complicated to allow anything but approximations" - John von Neumann 

## In this Chapter

We explain what constitutes a financial model and what are common uses of a model. We explain what makes an adept practitioner.

## What is a model?

A **model** represents aspects of the world around us distilled down into simpler, more tractable components. It is impossible to fully capture the everything that may affect the objects of our interest. 

For example, say we want to simulate the returns for the stocks in our retirement portfolio. It would be impossible to try to build a model which would capture all of the individual people working jobs and making decisions, weather events that damage property, political machinations, etc. Instead, we try to capture certain fundamental characteristics. For example, it is common to model equity returns as cumulative plusses and minuses from random movements where those movements have certain theoretical or historical characteristics. 

Whether we are using this model of equity returns to estimate available retirement income or replicate an exotic option price, a key aspect of the model is the **assumptions** used therein. For the retirement income scenario we might *assume* a healthy eight percent return on stocks and conclude that such a return will be sufficent to retire at age 53. Alternatively, we may assume that future returns will follow a stochastic path with a certain distribution of volatility and drift. These two assumption sets will produce **output** - results from our model that must be inpsected, questioned, and understood in the context of the "small world" of the model's mechansitic workings. Lastly, to be effective practitioners we must be able to contextualize the "small world" results withing the "large world" that exists around us.

More on the "small world" vs "large world": say that our model is one that discounts a fixed set of future cashflows using the US Treasury rate curve. If I run my model using current rates today, and then re-run my model tomorrow with the same future cashlows and the present value of those cashflows has increased by 5% I may ask why the result has changed so much in such a short period of time! In the "small", mechanistic world of the model I may be able to see that the rates I used to discount the cashflows with have fallen substantially. The "small world" answer is that the inputs have changed which produced a mechanical change in the output. The "big world" answer may be that the Federal Reserve lowered the Federal Funds Rate to prevent the economy from entering a deflationary recession. Of course, we can't completely explain the relation between our model and the real world (otherwise we could capture that relationship in our model!). An effective practition will always try to look up from the immediate work and take stock of how the world at large *is* or *is not* relfected in the model.

## Predictive versus Explanatory Models

Copernican versus Ptolemic models...