# Preface {.unnumbered}

This open-access book enables financial professionals and advanced students to apply the tools and concepts of computational and related sciences to their work.

Throughout these pages, you'll see how to effectively represent financial modeling ideas so they remain scalable, intelligible to collaborators, and robust against changing conditions. The book covers fundamentals in programming to advanced topics like parallelization and data visualization, always returning to practical applications in insurance, asset modeling, and beyond. 

The goal is straightforward: to empower financial professionals with the knowledge and confidence to manipulate computational tools in ways that reveal ever richer insights into the systems we seek to understand and influence.

This book is available in multiple formats: [HTML](http://ModernFinancialModeling.com), [PDF](http://ModernFinancialModeling.com/Modern-Financial-Modeling.pdf), and [EPUB](http://ModernFinancialModeling.com/Modern-Financial-Modeling.epub).

::: {.content-visible when-format="html"}
:::: callout-note

## Welcome to the Public Beta of MFM

In preparation for print editing, the book has entered a "public beta" phase. During this phase we will continue to refine the text based on reviews and feedback.

## Feedback

We invite you to provide feedback by submitting an issue at the book's [GitHub repository](https://github.com/alecloudenback/ModernFinancialModeling) or emailing [info@modernfinancialmodeling.com](mailto:info@modernfinancialmodeling.com?subject=MFM%20Inquiry).

## Interest in Updates

```{=html}
<iframe src="https://alecloudenback.notion.site/ebd/251c01c1993680a69beef5253b344e97" width="100%" height="600" frameborder="0" allowfullscreen />
```

::::
:::