# Set up Julia and the Computing Environment {#sec-julia-basics}

## Installation

Julia is open source and can be downloaded from [JuliaLang.org](https://JuliaLang.org) and is available for all major operating systems. After you download and install, then you have Julia installed and can access the **REPL**, or Read-Eval-Print-Loop, which can run complete programs or [function as powerful day-to-day calculator](https://krasjet.com/rnd.wlk/julia/). However, many people find it more comfortable to work in a text editor or **IDE** (Integrated Development Environment).

If you are looking for managed installations with a curated set of packages for use within an organization, there are ways to self-host package repositories and otherwise administratively manage packages. [Julia Computing](https://juliacomputing.com/) offers managed support with enterprise solutions, including push-button cloud compute capabilities.

## Package Management

Julia comes with `Pkg`, a built-in package manger. With it, you can install packages, pin certain versions, recreate environments with the same set of dependencies, and upgrade/remove/develop packages easily. It's one of the things that *just works* and makes Julia stand out versus alternative languages that don't have a de-facto way of managing or installing packages.

Package installation is accomplished interactively in the REPL or executing commands.

-   In the REPL, you can change to the Package Management Mode by hitting `]` and, e.g., `add DataFrames CSV` to install the two packages. Hit `[backspace]` to exit that mode in the REPL.
-   The same operation without changing REPL modes would be: `using Pkg; Pkg.add(["DataFrames", "CSV"])`

Related to packages, are **environments** which are a self-contained workspaces for your code. This lets you install only packages that are relevant to the current work. It also lets you 'remember' the exact set of packages and versions that you used. In fact, you can share the environment with others, and it will be able to recreate the same environment as when you ran the code. This is accomplished via a `Project.toml` file, which tracks the direct dependencies you've added, along with details about your project like its version number. The `Manifest.toml` tracks the entire dependency tree.

Reproducibility via the environment tools above is a really key aspect that will ensure Julia code is consistent across time and users, which is important for financial controls.

## Editors

Because Julia is very extensible and amenable to analysis of its own code, you can typically find plugins for whatever tool you prefer to write code in. A few examples:

### Visual Studio Code

Visual Studio Code is a free editor from Microsoft. There's a full-featured [Julia plugin](https://www.julia-vscode.org/) available, which will help with auto-completion, warnings, and other code hints that you might find in a dedicated editor (e.g. PyCharm or RStudio). Like those tools, you can view plots, search documentation, show datasets, debug, and manage version control.

### Notebooks

Notebooks are typically more interactive environments than text editors - you can write code in cells and see the results side-by-side.

The most popular notebook tool is Jupyter ("Julia, Python, R"). It is widely used and fits in well with exploratory data analysis or other interactive workflows. It can be installed by adding the [`IJulia.jl`](https://github.com/JuliaLang/IJulia.jl) package.

[`Pluto.jl`](https://plutojl.org/) is a newer tool, which adds reactivity and interactivity. It is also more amenable to version control than Jupyter notebooks because notebooks are saved as plain Julia scripts. Pluto is unique to Julia because of the language's ability to introspect and analyze dependencies in its own code. Pluto also has built-in package/environment management, meaning that Pluto notebooks contains all the code needed to reproduce results (as long as Julia and Pluto are installed).

## REPL

The **REPL** (or **Read Eval Print Loop**) is the command line interface in which you can start a julia session, enter expressions to be evaluated, and see the results interactively. When you start the Julia executable, it will start a REPL session by default. It looks like the following:

``` julia-repl
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-rc4 (2024-09-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> 2+4
6

julia> ans + 3
9
```

### REPL Modes

The REPL can be changed into different modes, which allow for easier use of specialized features. When in a special mode, you can hit `Backspace` until you are returned to the base mode (which will show `julia>`). Some examples include those that are built-in to Julia (@tbl-julia-modes)and we also highlight a few modes that are facilitated by packages (@tbl-julia-modes-community). The hyperlink for the mode links to the associated documentation for further reference.

| Mode | Prompt | Key | Description |
|------------------|------------------|------------------|------------------|
| [Julia](https://docs.julialang.org/en/v1/stdlib/REPL/) (the default mode) | `julia>` | n/a | The basic interactive mode for the Julia REPL. |
| [Pkg](https://pkgdocs.julialang.org/v1/repl/) | `(@v1.11) pkg>` | `]` | Package and environment management mode (the environment within the parenthesis is the currently activated environment). |
| [Help](https://docs.julialang.org/en/v1/stdlib/REPL/#Help-mode) | `help?>` | `?` | A mode to show docstrings and READMEs for packages. |
| [Shell](https://docs.julialang.org/en/v1/stdlib/REPL/#man-shell-mode) | `shell>` | `;` | A mode which passes expressions to your default command line. This is useful to interact with the computer without needing to leave the Julia REPL. |

: Julia comes with multiple REPL modes which provide easier access to some key functionality. {#tbl-julia-modes}

| Mode | Prompt | Key | Description |
|------------------|------------------|------------------|------------------|
| [SQL, via SQLREPL.jl](https://github.com/c42f/SQLREPL.jl) | `SQL>` | `)` | A mode to write and execute queries against a database. |
| [GPT via REPLGPT.jl](https://github.com/ThatcherC/ReplGPT.jl) | `(@v1.11) pkg>` | `}` | Chat with ChatGPT from within the Julia REPL. |

: Julia is extensible and has many community created REPL modes. {#tbl-julia-modes-community}