<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Computational Thinking for Actuaries and Financial Professionals - 10&nbsp; Statistical Inference and Information Theory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./computational-thinking.html" rel="next">
<link href="./software.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<script data-goatcounter="https://julia-fin-book.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./conceptual-foundations.html">Conceptual Foundations</a></li><li class="breadcrumb-item"><a href="./statistics.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Statistical Inference and Information Theory</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Computational Thinking for Actuaries and Financial Professionals</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cover_draft.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Draft of Cover</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./why-program.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Why Program?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./why-julia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Why use Julia?</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./conceptual-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conceptual Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./elements-of-financial-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Elements of Financial Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-of-programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Elements of Programming</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./patterns-abstraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Patterns of Abstraction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./elements-of-compsci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Elements of Computer Science</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hardware.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Hardware and It’s Implications</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Applying Software Engineering Principles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Statistical Inference and Information Theory</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./computational-thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computational Thinking in an Actuarial and Financial Context</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./autodiff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Automatic Differentiation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Optimization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sensitivity-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Sensitivity Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stochastic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Stochastic Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visiualizations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Matrices and Their Uses</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Learning from Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Applications in Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stochastic-mortality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Stochastic Mortality Projections</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scenario-generation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Scenario Generation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./similarity-calculation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Similarity Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./portfolio-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Portfolio Optimization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./other-techniques.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Other Useful Techniques</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./appendices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./julia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Set up Julia and the Computing Environment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./environment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Environment and Package Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ecosystem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">The Julia Ecosystem Today</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#information-theory" id="toc-information-theory" class="nav-link active" data-scroll-target="#information-theory"><span class="header-section-number">10.1</span> Information Theory</a>
  <ul class="collapse">
  <li><a href="#example-classificaiton" id="toc-example-classificaiton" class="nav-link" data-scroll-target="#example-classificaiton"><span class="header-section-number">10.1.1</span> Example: Classificaiton</a></li>
  <li><a href="#maxium-entropy-distributions" id="toc-maxium-entropy-distributions" class="nav-link" data-scroll-target="#maxium-entropy-distributions"><span class="header-section-number">10.1.2</span> Maxium Entropy Distributions</a></li>
  </ul></li>
  <li><a href="#bayes-rule" id="toc-bayes-rule" class="nav-link" data-scroll-target="#bayes-rule"><span class="header-section-number">10.2</span> Bayes’ Rule</a>
  <ul class="collapse">
  <li><a href="#example-model-selection-via-likelihoods" id="toc-example-model-selection-via-likelihoods" class="nav-link" data-scroll-target="#example-model-selection-via-likelihoods"><span class="header-section-number">10.2.1</span> Example: Model Selection via Likelihoods</a></li>
  </ul></li>
  <li><a href="#sec-modern-bayes" id="toc-sec-modern-bayes" class="nav-link" data-scroll-target="#sec-modern-bayes"><span class="header-section-number">10.3</span> Bridging to Modern Bayesian Statistics?</a></li>
  <li><a href="#advantages-of-the-bayesian-approach" id="toc-advantages-of-the-bayesian-approach" class="nav-link" data-scroll-target="#advantages-of-the-bayesian-approach"><span class="header-section-number">10.4</span> Advantages of the Bayesian Approach</a></li>
  <li><a href="#challenges-with-the-bayesian-approach" id="toc-challenges-with-the-bayesian-approach" class="nav-link" data-scroll-target="#challenges-with-the-bayesian-approach"><span class="header-section-number">10.5</span> Challenges with the Bayesian Approach</a></li>
  <li><a href="#why-now" id="toc-why-now" class="nav-link" data-scroll-target="#why-now"><span class="header-section-number">10.6</span> Why Now?</a></li>
  <li><a href="#subjectivity-of-the-priors" id="toc-subjectivity-of-the-priors" class="nav-link" data-scroll-target="#subjectivity-of-the-priors"><span class="header-section-number">10.7</span> Subjectivity of the Priors?</a>
  <ul class="collapse">
  <li><a href="#subjectivity-as-a-feature" id="toc-subjectivity-as-a-feature" class="nav-link" data-scroll-target="#subjectivity-as-a-feature"><span class="header-section-number">10.7.1</span> Subjectivity as a Feature</a></li>
  <li><a href="#subjectivity-as-a-flaw" id="toc-subjectivity-as-a-flaw" class="nav-link" data-scroll-target="#subjectivity-as-a-flaw"><span class="header-section-number">10.7.2</span> Subjectivity as a Flaw</a></li>
  <li><a href="#maximum-entropy-distributions" id="toc-maximum-entropy-distributions" class="nav-link" data-scroll-target="#maximum-entropy-distributions"><span class="header-section-number">10.7.3</span> Maximum Entropy Distributions</a></li>
  </ul></li>
  <li><a href="#bayesian-versus-machine-learning" id="toc-bayesian-versus-machine-learning" class="nav-link" data-scroll-target="#bayesian-versus-machine-learning"><span class="header-section-number">10.8</span> Bayesian Versus Machine Learning</a></li>
  <li><a href="#implications-for-risk-management" id="toc-implications-for-risk-management" class="nav-link" data-scroll-target="#implications-for-risk-management"><span class="header-section-number">10.9</span> Implications for Risk Management</a></li>
  <li><a href="#paving-the-way-forward-for-actuaries" id="toc-paving-the-way-forward-for-actuaries" class="nav-link" data-scroll-target="#paving-the-way-forward-for-actuaries"><span class="header-section-number">10.10</span> Paving the Way Forward for Actuaries</a>
  <ul class="collapse">
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">10.10.1</span> Further Reading</a></li>
  </ul></li>
  <li><a href="#httpsdata.ca.govdatasetannual-precipitation-data-for-northern-california-1944-current" id="toc-httpsdata.ca.govdatasetannual-precipitation-data-for-northern-california-1944-current" class="nav-link" data-scroll-target="#httpsdata.ca.govdatasetannual-precipitation-data-for-northern-california-1944-current"><span class="header-section-number">11</span> https://data.ca.gov/dataset/annual-precipitation-data-for-northern-california-1944-current</a></li>
  <li><a href="#point-we-can-use-the-likelihood-component-of-bayes-rule-to-compare-models" id="toc-point-we-can-use-the-likelihood-component-of-bayes-rule-to-compare-models" class="nav-link" data-scroll-target="#point-we-can-use-the-likelihood-component-of-bayes-rule-to-compare-models"><span class="header-section-number">12</span> Point: we can use the likelihood component of bayes rule to compare models</a></li>
  <li><a href="#three-models-are-compared-normal-lognormal-and-gamma-pearson-iii" id="toc-three-models-are-compared-normal-lognormal-and-gamma-pearson-iii" class="nav-link" data-scroll-target="#three-models-are-compared-normal-lognormal-and-gamma-pearson-iii"><span class="header-section-number">13</span> three models are compared: normal, lognormal, and gamma (Pearson III)</a></li>
  <li><a href="#httpsstats.stackexchange.comquestions55563estimating-parameters-of-log-pearson-iii-distribution-in-r" id="toc-httpsstats.stackexchange.comquestions55563estimating-parameters-of-log-pearson-iii-distribution-in-r" class="nav-link" data-scroll-target="#httpsstats.stackexchange.comquestions55563estimating-parameters-of-log-pearson-iii-distribution-in-r"><span class="header-section-number">14</span> https://stats.stackexchange.com/questions/55563/estimating-parameters-of-log-pearson-iii-distribution-in-r</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"><span class="header-section-number">15</span> </a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./conceptual-foundations.html">Conceptual Foundations</a></li><li class="breadcrumb-item"><a href="./statistics.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Statistical Inference and Information Theory</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Statistical Inference and Information Theory</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>“My greatest concern was what to call [the amount of unpredictabilty in a random outcome]. I thought of calling it ‘information,’ but the word was overly used, so I decided to call it ‘uncertainty.’ When I discussed it with John von Neumann, he had a better idea. Von Neumann told me, ‘You should call it entropy, for two reasons. In the first place your uncertainty function has been used in statistical mechanics under that name, so it already has a name. In the second place, and more important, no one really knows what entropy really is, so in a debate you will always have the advantage.’”- Claude Shannon (1971)</p>
</blockquote>
<section id="information-theory" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="information-theory"><span class="header-section-number">10.1</span> Information Theory</h2>
<p>Probability, statistics, machine learning, signal processing, and even physics have a foundational link in <strong>information theory</strong> which is the description and analysis of how much useful data is contained within something.</p>
<p>Let’s consider the following number that we encounter while reading a report which contains estimates of total amount of assets held. Unfortunately, for one reason or another one of the digits is not visible to you. Here’s what you can read, with the <code>_</code> indicating that the digit is not visible:</p>
<pre><code>32,000,_00</code></pre>
<p>Now you probably already formed an opinion on what the missing number is, but let’s look at how we can quantify the analysis.</p>
<p>Given that we know the number was an estimate and the tendency of humans to like nice round numbers, our <strong>prior assumption</strong> for what the probability of the missing digit is may be something like the <span class="math inline">\(p(x_i)\)</span> row of <a href="#tbl-digit-information-human" class="quarto-xref">Table&nbsp;<span>10.1</span></a>. We shall call the individual outcomes <span class="math inline">\(x_i\)</span> and the overall set of probabilities <span class="math inline">\(\{x_0,x_1,...x_9\}\)</span> is called <span class="math inline">\(X\)</span>.</p>
<p>The information content of an outcome, <span class="math inline">\(h(x)\)</span> is measured in bits and defined as<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</p>
<p><span id="eq-information"><span class="math display">\[
h(x_i) = \text{log}_2\frac{1}{p(x_i)}
\tag{10.1}\]</span></span></p>
<p>So if we were to find out that the missing digit were indeed <code>0</code>, we have gained less information relative to our expectation than if the missing digit were anything other than <code>0</code> .</p>
<p>We can characterize the entire distribution <span class="math inline">\(X\)</span> via the <strong>entropy,</strong> <span class="math inline">\(H(X)\)</span>, of a probability set is the ensemble’s average information content:</p>
<p><span id="eq-entropy"><span class="math display">\[
H(X) = \sum{p(x_i)\text{log}_2}\frac{1}{p(x_i)}
\tag{10.2}\]</span></span></p>
<p>The entropy <span class="math inline">\(H(X)\)</span> of the presumed outcomes in <a href="#tbl-digit-information-human" class="quarto-xref">Table&nbsp;<span>10.1</span></a> distirubtion of outcomes is <span class="math inline">\(0.722 \text{bits}\)</span>.</p>
<div id="tbl-digit-information-human" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-digit-information-human-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.1: Probability distribution of missing digit knowing human inclinations to prefer round numbers when estimating. $$
</figcaption>
<div aria-describedby="tbl-digit-information-human-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(x_i\)</span></td>
<td>0</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
<td>8</td>
<td>9</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p(x_i)\)</span></td>
<td>.91</td>
<td>.01</td>
<td>.01</td>
<td>.01</td>
<td>.01</td>
<td>.01</td>
<td>.01</td>
<td>.01</td>
<td>.01</td>
<td>.01</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(h(x_i)\)</span></td>
<td>0.136</td>
<td>6.644</td>
<td>6.644</td>
<td>6.644</td>
<td>6.644</td>
<td>6.644</td>
<td>6.644</td>
<td>6.644</td>
<td>6.644</td>
<td>6.644</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Note that we have take a view on the probability distribution for the missing digit, and we’ll refer to this as the <strong>prior assumption</strong> (or just <strong>prior</strong>). This is an opinionated assumption, so what if we had another colleague who beleived humans are completely rational and without bias for certaim numbers. They would then be arguing for a prior assumed distribution consistent with <a href="#tbl-digit-information-unifrom" class="quarto-xref">Table&nbsp;<span>10.2</span></a>.</p>
<p>With the uniform prior assumption, <span class="math inline">\(H(X) = 3.322 \text{bits}\)</span> and <span class="math inline">\(h(x_i)\)</span> is also unifrom. We will not prove it here, but a uniform probability over a set of outcomes is the highest entropy distribution that can be assumed.</p>
<div id="tbl-digit-information-unifrom" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-digit-information-unifrom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.2: Probability distribution of missing digit with uniform, maximal entropy for the assumed probability distribution.
</figcaption>
<div aria-describedby="tbl-digit-information-unifrom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(x_i\)</span></td>
<td>0</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
<td>8</td>
<td>9</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p(x_i)\)</span></td>
<td>.10</td>
<td>.10</td>
<td>.10</td>
<td>.10</td>
<td>.10</td>
<td>.10</td>
<td>.10</td>
<td>.10</td>
<td>.10</td>
<td>.10</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(h(x_i)\)</span></td>
<td>3.322</td>
<td>3.322</td>
<td>3.322</td>
<td>3.322</td>
<td>3.322</td>
<td>3.322</td>
<td>3.322</td>
<td>3.322</td>
<td>3.322</td>
<td>3.322</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="example-classificaiton" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="example-classificaiton"><span class="header-section-number">10.1.1</span> Example: Classificaiton</h3>
<p>In this example, we will determine the optimal splits for a decision tree<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> based on the information gained at each node in the tree.</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DataFrames</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>employed <span class="op">=</span> [<span class="cn">true</span>, <span class="cn">false</span>, <span class="cn">true</span>, <span class="cn">true</span>, <span class="cn">true</span>, <span class="cn">false</span>, <span class="cn">false</span>, <span class="cn">true</span>]</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>good_credit <span class="op">=</span> [<span class="cn">true</span>, <span class="cn">true</span>, <span class="cn">false</span>, <span class="cn">true</span>, <span class="cn">false</span>, <span class="cn">false</span>, <span class="cn">false</span>, <span class="cn">true</span>]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>default <span class="op">=</span> [<span class="cn">true</span>, <span class="cn">false</span>, <span class="cn">true</span>, <span class="cn">true</span>, <span class="cn">true</span>, <span class="cn">true</span>, <span class="cn">false</span>, <span class="cn">true</span>]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>default_data <span class="op">=</span> <span class="fu">DataFrame</span>(; employed, good_credit, default)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-default-data" class="cell quarto-float anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-default-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.3: Fictional data regarding loan attributes and whether or not a loan defaulted before it’s maturity.
</figcaption>
<div aria-describedby="tbl-default-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>
<div><div style="float: left;"><span>8×3 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">employed</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">good_credit</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">default</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Bool">Bool</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Bool">Bool</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Bool">Bool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">false</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">7</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">false</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">8</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</figure>
</div>
</div>
<p>The entropy of the default rate data is, per <a href="#eq-entropy" class="quarto-xref">Equation&nbsp;<span>10.2</span></a>:</p>
<div id="da64780e" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>H0 <span class="op">=</span> <span class="kw">let</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    p1 <span class="op">=</span> <span class="fu">sum</span>(default_data.default) <span class="op">/</span> <span class="fu">nrow</span>(default_data)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    p2 <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> p1</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    p1 <span class="op">*</span> <span class="fu">log2</span>(<span class="fl">1</span> <span class="op">/</span> p1) <span class="op">+</span> p2 <span class="op">*</span> <span class="fu">log</span>(<span class="fl">1</span> <span class="op">/</span> p2) </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>0.6578517147391054</code></pre>
</div>
</div>
<p>Our goal is to determine which attribute (<code>employed</code> or <code>good_credit</code>) to use as the first split in the decision tree. We will decide this by calculating the information gain, which is the difference in entropy between the prior node and the candidate node. In our case we start with <code>H0</code> as calculated above for the output variable <code>default</code> and calculate the difference in entropy between it and the average entropy of the data if we split on that node. <strong>Information gain</strong>, <span class="math inline">\(IG(inputs, attributes)\)</span>, is:</p>
<p><span class="math display">\[
...
\]</span></p>
<p>Let’s first consider splitting the tree based on the <code>employed</code> status. We will calculate the entropy of each subset: with employment and without employment.</p>
<p>If we split the data based on being employed, we’d get two sub-datasets:</p>
<div id="5b690868" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df_employed <span class="op">=</span> <span class="fu">filter</span>(<span class="op">:</span>employed <span class="op">=&gt;</span> <span class="op">==</span>(<span class="cn">true</span>),default_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>
<div><div style="float: left;"><span>5×3 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">employed</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">good_credit</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">default</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Bool">Bool</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Bool">Bool</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Bool">Bool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">true</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>and</p>
<div id="0ac3d38a" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df_unemployed <span class="op">=</span> <span class="fu">filter</span>(<span class="op">:</span>employed <span class="op">=&gt;</span> <span class="op">==</span>(<span class="cn">false</span>),default_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>
<div><div style="float: left;"><span>3×3 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">employed</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">good_credit</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">default</th>
</tr>
<tr class="odd subheader headerLastRow">
<th class="rowNumber" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Bool">Bool</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Bool">Bool</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Bool">Bool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">true</td>
<td style="text-align: right;">false</td>
</tr>
<tr class="even">
<td class="rowNumber" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">true</td>
</tr>
<tr class="odd">
<td class="rowNumber" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">false</td>
<td style="text-align: right;">false</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>let’s call it’s entropy <code>H_employed</code>, which should be zero because there is no variability in the <code>default</code> outcome for this subset.</p>
<div id="dde3c54d" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="annotated-cell-6"><pre class="sourceCode julia code-annotation-code code-with-copy code-annotated"><code class="sourceCode julia"><span id="annotated-cell-6-1"><a href="#annotated-cell-6-1" aria-hidden="true" tabindex="-1"></a>H_employed <span class="op">=</span> <span class="kw">let</span></span>
<span id="annotated-cell-6-2"><a href="#annotated-cell-6-2" aria-hidden="true" tabindex="-1"></a>    p1 <span class="op">=</span> <span class="fu">sum</span>(df_employed.default) <span class="op">/</span> <span class="fu">nrow</span>(df_employed)</span>
<span id="annotated-cell-6-3"><a href="#annotated-cell-6-3" aria-hidden="true" tabindex="-1"></a>    p2 <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> p1</span>
<span id="annotated-cell-6-4"><a href="#annotated-cell-6-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># p1 * log2(1 / p1) + p2 * log(1 / p2) </span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-6" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-6-5" class="code-annotation-target"><a href="#annotated-cell-6-5" aria-hidden="true" tabindex="-1"></a>    p1 <span class="op">*</span> <span class="fu">log2</span>(<span class="fl">1</span> <span class="op">/</span> p1) <span class="op">+</span> <span class="fl">0</span></span>
<span id="annotated-cell-6-6"><a href="#annotated-cell-6-6" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-6" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-6" data-code-lines="5" data-code-annotation="1">In the case of <span class="math inline">\(p_i = 0\)</span> the value of <span class="math inline">\(h\)</span> (the second term in the sum above) is taken to be <span class="math inline">\(0\)</span>, which is consistent with the <span class="math inline">\(\lim_{p\to0^+}p\log (p) = 0\)</span>.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>0.0</code></pre>
</div>
</div>
<p>And the correspoding candidate leaf is <code>H_unemployed</code>:</p>
<div id="065f562a" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>H_unemployed <span class="op">=</span> <span class="kw">let</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    p1 <span class="op">=</span> <span class="fu">sum</span>(df_unemployed.default) <span class="op">/</span> <span class="fu">nrow</span>(df_unemployed)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    p2 <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> p1</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    p1 <span class="op">*</span> <span class="fu">log2</span>(<span class="fl">1</span> <span class="op">/</span> p1) <span class="op">+</span> p2 <span class="op">*</span> <span class="fu">log</span>(<span class="fl">1</span> <span class="op">/</span> p2)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>0.7986309056458281</code></pre>
</div>
</div>
<p>The average of the two is weighted by the size of the data that would fall into each leaf:</p>
<div id="d79db7ca" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>H1_employment <span class="op">=</span> <span class="kw">let</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    p_emp <span class="op">=</span> <span class="fu">nrow</span>(df_employed) <span class="op">/</span> <span class="fu">nrow</span>(default_data)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    p_unemp <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> p_emp</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    p_emp <span class="op">*</span> H_employed <span class="op">+</span> p_unemp <span class="op">*</span> H_unemployed</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>0.29948658961718555</code></pre>
</div>
</div>
<p>The information gain for splitting the tree using employment status is the difference between the root entropy and the entropy of the employment split:</p>
<div id="c96109bf" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>IG_employment <span class="op">=</span> H0 <span class="op">-</span> H1_employment</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>0.35836512512191987</code></pre>
</div>
</div>
<p>We could repeat the analyis to determine the information gain if we were to split the tree based on having good credit. However, given that there are only two attributes we can already conclude that <code>employed</code> is a better attribute to split the data on. This is because the information gain of <code>IG_employment</code> (0.358) is the majority of the overall entropy <code>H0</code> (0.658). Entropy is always additive and you cannot have negative entropy, therefore no other other attribute could have greater information gain. This also matches our intuition when looking at <a href="#tbl-default-data" class="quarto-xref">Table&nbsp;<span>10.3</span></a> as the eye can spot a higher correlation between <code>employed</code> and <code>default</code> than <code>good_credit</code> and <code>default</code>.</p>
<p>The above example demonstrates how we can use information theory to create more optimal inferences on data.</p>
</section>
<section id="maxium-entropy-distributions" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="maxium-entropy-distributions"><span class="header-section-number">10.1.2</span> Maxium Entropy Distributions</h3>
<p>Why is information theory a useful concept? Many financial models are statistical in nature and concepts of randomness and entropy are foundational. For example, when trying to estimate parameter distributions or assume a distribution for a random process you can lean on information theory to use the most conservative choice: the distribution with the highest entropy given known constraints. These distributions are referred to as <strong>maximum entropy distributions</strong>. Some discussion of maximum entropy distributions in the context of risk assessment is available in an article by Duracz<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. probability distributions and risk asses</p>
<div id="tbl-MEDs" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-MEDs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.4: Maximum Entropy Distributions and the conditions under which they are applicable.
</figcaption>
<div aria-describedby="tbl-MEDs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Constraint</th>
<th>Discrete Distribution</th>
<th>Continuous Distribution</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bounded range</td>
<td>Uniform (discrete)</td>
<td>Uniform (continuous)</td>
<td></td>
</tr>
<tr class="even">
<td>Mean is finite, two possible values</td>
<td>Binomial</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Mean is finite</td>
<td>Geometric</td>
<td>Exponential</td>
<td></td>
</tr>
<tr class="even">
<td>Mean is finite and range is &gt; zero</td>
<td></td>
<td>Gamma</td>
<td></td>
</tr>
<tr class="odd">
<td>Mean and Variance is finite</td>
<td></td>
<td>Guassian (Normal)</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The distributions in <a href="#tbl-MEDs" class="quarto-xref">Table&nbsp;<span>10.4</span></a> arise again and again in nature because of the second law of thermodynamics - nature likes to have constantly increasing entropy and therefore it should be no surprise (random) processes that maximize entropy pop up all over the place. As an example, let’s look at processes that behave like the Gaussian (Normal) distribution.</p>
<p>A random walk can be viewed as the cumulative impact of nudges pushing in opposite directions. This behavior culminates in the random, terminal position being able to be described by a Gaussian distribution. The center of a Gaussian distribution is “thick” because there are many more ways for the cumulative total nudges to mostly cancel out, while its increasingly rare to end up further and further from the starting point (mean). The distribution then spreads out as flat (randomly) as it can while still maintaining the constraint of having a given, finite variance. Any other continuous distribution that has the same mean and variance has lower entropy than the Guassian.</p>
</section>
</section>
<section id="bayes-rule" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="bayes-rule"><span class="header-section-number">10.2</span> Bayes’ Rule</h2>
<p>The minister and statistician Thomas Bayes derived a relationship of conditional probabilities that we today know as <strong>Bayes’ Rule</strong>, commonly written as:</p>
<p><span class="math display">\[
P(H|D) = \frac{P(D|H) \times P(H)}{P(D)}
\]</span></p>
<p>The components of this are:</p>
<ul>
<li><span class="math inline">\(P(H∣D)\)</span> is the conditional probability of event <span class="math inline">\(H\)</span> occurring given that <span class="math inline">\(D\)</span> is true.</li>
<li><span class="math inline">\(P(D∣H)\)</span> is the conditional probability of event <span class="math inline">\(D\)</span> occurring given that <span class="math inline">\(H\)</span> is true.</li>
<li><span class="math inline">\(P(H)\)</span> is the prior probability of event <span class="math inline">\(H\)</span>.</li>
<li><span class="math inline">\(P(D)\)</span> is the prior probability of event <span class="math inline">\(D\)</span>.</li>
</ul>
<p>If we take the following:</p>
<ul>
<li><span class="math inline">\(D\)</span> is the available data</li>
<li><span class="math inline">\(H\)</span> is our hypothesis</li>
</ul>
<p>Then we can draw conclusions about the probability of a hypothesis being true given the observed data. When thought about this way, Bayes’ rule is often described as:</p>
<p><span class="math display">\[
\text{posterior} = \frac{\text{likelihood} \times \text{prior}}{\text{evidence}}
\]</span></p>
<p>This is a very useful framework, which we’ll return to more completely in <a href="#sec-modern-bayes" class="quarto-xref"><span>Section 10.3</span></a>. First, let’s look at combining information theory and Bayes’ rule in an applied example.</p>
<section id="example-model-selection-via-likelihoods" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="example-model-selection-via-likelihoods"><span class="header-section-number">10.2.1</span> Example: Model Selection via Likelihoods</h3>
</section>
</section>
<section id="sec-modern-bayes" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="sec-modern-bayes"><span class="header-section-number">10.3</span> Bridging to Modern Bayesian Statistics?</h2>
<p>A Bayesian statistical model has four main components to focus on:</p>
<ol type="1">
<li><strong>Prior</strong> encoding assumptions about the random variables related to the problem at hand, before conditioning on the data.</li>
<li>A <strong>Model</strong> that defines how the random variables give rise to the observed outcome.</li>
<li><strong>Data</strong> that we use to update our prior assumptions.</li>
<li><strong>Posterior</strong> distributions of our random variables, conditioned on the observed data and our model</li>
</ol>
<p>Having defined the first two components and collected our data, the workflow involves computationally sampling the posterior distribution, often using a technique called Markov Chain Monte-Carlo (MCMC). The result is a series of values that are sampled statistically from the posterior distribution.</p>
</section>
<section id="advantages-of-the-bayesian-approach" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="advantages-of-the-bayesian-approach"><span class="header-section-number">10.4</span> Advantages of the Bayesian Approach</h2>
<p>The main advantages of this approach over traditional actuarial techniques are:</p>
<ol type="1">
<li><strong>Focus on distributions rather than point estimates of the posterior’s mean or mode.</strong> We are often interested in the distribution of the parameters and a focus on a single parameter estimate will understate the risk distribution.</li>
<li><strong>Model flexibility.</strong> A Bayesian model can be as simple as an ordinary linear regression, but as complex as modeling a full insurance mechanics.</li>
<li><strong>Simpler mental model.</strong> Fundamentally, Bayes’ theorem could be distilled down to an approach where you count the ways that things could occur and update the probabilities accordingly.</li>
<li><strong>Explicit Assumptions.</strong>: Enumerating the random variables in your model and explicitly parameterizing prior assumptions avoids ambiguity of the assumptions inside the statistical model.</li>
</ol>
</section>
<section id="challenges-with-the-bayesian-approach" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="challenges-with-the-bayesian-approach"><span class="header-section-number">10.5</span> Challenges with the Bayesian Approach</h2>
<p>With the Bayesian approach, there are a handful of things that are challenging. Many of the listed items are not unique to the Bayesian approach, but there are different facets of the issues that arise.</p>
<ol type="1">
<li><strong>Model Construction</strong>. One must be thoughtful about the model and how variables interact. However, with the flexibility of modeling, you can apply (actuarial) science to makes better models!</li>
<li><strong>Model Diagnostics</strong>. Instead of R^2 values, there are unique diagnostics that one must monitor to ensure that the posterior sampling worked as intended.</li>
<li><strong>Model Complexity and Size of Data</strong>. The sampling algorithms are computationally intensive - as the amount of data grows and model complexity grows, the runtime demands cluster computing.</li>
<li><strong>Model Representation</strong>. The statistical derivation of the posterior can only reflect the complexity of the world as defined by your model. A Bayesian model won’t automatically infer all possible real-world relationships and constraints.</li>
</ol>
</section>
<section id="why-now" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="why-now"><span class="header-section-number">10.6</span> Why Now?</h2>
<p>There are both philosophical and practical reasons why Bayesian analysis is rapidly changing the statistical landscape.</p>
<p><em>Philosophically</em>, one of the main reasons why Bayesian thinking is appealing is its ability to provide a straightforward interpretation of statistical conclusions.</p>
<p>For example, when estimating an unknown quantity, a Bayesian probability interval can be directly understood as having a high probability of containing that quantity. In contrast, a frequentist confidence interval is typically interpreted only in the context of a series of similar inferences that could be made in repeated practice. In recent years, there has been a growing emphasis on interval estimation rather than hypothesis testing in applied statistics. This shift has strengthened the Bayesian perspective since it is likely that many users of standard confidence intervals intuitively interpret them in a manner consistent with Bayesian thinking.</p>
<p>Another meaningful way to understand the contrast between Bayesian and frequentist approaches is through the lens of decision theory, specifically how each view treats the concept of randomness. This perspective pertains to whether you regard the data being random or the parameters being random.</p>
<p>Frequentist statistics treats parameters as fixed and unknown, and the data as random — this is reflective of the view that data you collect is but one realization of an infinitely repeatable random process. Consequently, frequentist procedures, like hypothesis testing or confidence intervals, are generally based on the idea of long-run frequency or repeatable sampling.</p>
<p>Conversely, Bayesian statistics turns this on its head by treating the data as fixed — after all, once you’ve collected your data, it’s no longer random but a fixed observed quantity. Parameters, which are unknown, are treated as random variables. The Bayesian approach then allows us to use probability to quantify our uncertainty about these parameters.</p>
<p>The Bayesian approach tends to align more closely with our intuitive way of reasoning about problems. Often, you are given specific data and you want to understand what that particular set of data tells you about the world. You’re likely less interested in what might happen if you had infinite data, but rather in drawing the best conclusions you can from the data you do have.</p>
<p><em>Practically</em>, recent advances in computational power, algorithm development, and open-source libraries have enabled practitioners to adapt the Bayesian workflow.</p>
<p>Deriving the posterior distribution is analytically intractable so computational methods must be used. Advances in raw computing power only in the 1990’s made non-trivial Bayesian analysis possible, and recent advances in algorithms have made the computations more efficient. For example, one of the most popular algorithms, NUTS, was only published in the 2010’s.</p>
<p>Many problems require the use of compute clusters to manage runtime, but if there is any place to invest in understanding posterior probability distributions, it’s insurance companies trying to manage risk!</p>
<p>Moreover, the availability of open-source libraries, such as Turing.jl, PyMC3, and Stan provide access to the core routines in an accessible interface.</p>
</section>
<section id="subjectivity-of-the-priors" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="subjectivity-of-the-priors"><span class="header-section-number">10.7</span> Subjectivity of the Priors?</h2>
<p>There are two ways one might react to subjectivity in a Bayesian context: It’s a feature that should be embraced or it’s a flaw that should be avoided.</p>
<section id="subjectivity-as-a-feature" class="level3" data-number="10.7.1">
<h3 data-number="10.7.1" class="anchored" data-anchor-id="subjectivity-as-a-feature"><span class="header-section-number">10.7.1</span> Subjectivity as a Feature</h3>
<p><strong>A Bayesian approach to defining a statistical model is an approach that allows for explicitly incorporating actuarial judgment.</strong> Encoding assumptions into a Bayesian model forces the actuary to be explicit about otherwise fuzzy predilections. The explicit assumption is also more amenable to productive debate about its merits and biases than an implicit judgmental override.</p>
</section>
<section id="subjectivity-as-a-flaw" class="level3" data-number="10.7.2">
<h3 data-number="10.7.2" class="anchored" data-anchor-id="subjectivity-as-a-flaw"><span class="header-section-number">10.7.2</span> Subjectivity as a Flaw</h3>
<p>Subjectivity is inherent in all useful statistical methods. Subjectivity in traditional approaches include how the data was collected, which hypothesis to test, what significant levels to use, and assumptions about the data-generating processes.</p>
<p>In fact, the “objective” approach to null hypothesis testing is so prone to abuse and misinterpretation that in 2016, the American Statistical Association issued a statement intended to steer statistical analysis into a “post p&lt;0.05 era.” That “p&lt;0.05” approach is embedded in most traditional approaches to actuarial credibility<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> and therefore should be similarly reconsidered.</p>
</section>
<section id="maximum-entropy-distributions" class="level3" data-number="10.7.3">
<h3 data-number="10.7.3" class="anchored" data-anchor-id="maximum-entropy-distributions"><span class="header-section-number">10.7.3</span> Maximum Entropy Distributions</h3>
<p>Further, when assigning a prior assumption to a random variable, there are mathematically most conservative choices to pull from. These are called Maximum Entropy Distributions (MED) and it can be shown that for certain minimal constraints these are the information-theoretic least informative choices. Least informative means that the prior will have the least influence on the resulting posterior distribution.</p>
<p>For example, if all you know is that the mean of a random process is positive, then the Exponential Distribution is your MED. If you know that a mean and variance must exist for the process, then the Normal distribution is your MED. If you know nothing at all, you can use a Uniform distribution for the possible values.</p>
</section>
</section>
<section id="bayesian-versus-machine-learning" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="bayesian-versus-machine-learning"><span class="header-section-number">10.8</span> Bayesian Versus Machine Learning</h2>
<p>Machine learning (ML) is <em>fully compatible</em> with Bayesian analysis - one can derive posterior distributions for the ML parameters like any other statistical model and the combination of approaches may be fruitful in practice.</p>
<p>However, to the extent that actuaries have leaned on ML approaches due to the shortcomings of traditional actuarial approaches, Bayesian modeling may provide an attractive alternative without resorting to notoriously finicky and difficult-to-explain ML models. The Bayesian framework provides an explainable model and offers several analytic extensions beyond the scope of this introductory article:</p>
<ul>
<li>Causal Modeling: Identifying not just correlated relationships, but causal ones, in contexts where a traditional experiment is unavailable.</li>
<li>Bayes Action: Optimizing a parameter for, e.g., a CTE95 level instead of a parameter mean.</li>
<li>Information Criterion: Principled techniques to compare model fit and complexity.</li>
<li>Missing data: Mechanisms to handle the different kinds of missing data.</li>
<li>Model averaging: Posteriors can be combined from different models to synthesize different approaches.</li>
</ul>
</section>
<section id="implications-for-risk-management" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="implications-for-risk-management"><span class="header-section-number">10.9</span> Implications for Risk Management</h2>
<p>Like Bayes’ Formula itself, another aspect of actuarial literature that is taught but often glossed over in practice is the difference between process risk (volatility), parameter risk, and model formulation risk. Often when performing analysis that relies on stochastic result, in practice only process/volatility risk is assessed.</p>
<p>Bayesian statistics provides the tools to help actuaries address parameter risk and model formulation. The posterior distribution of parameters derived is consistent with the observed data and modeled relationships. This posterior distribution of parameters can then be run as an additional dimension to the risk analysis.</p>
<p>Additionally, best practices include skepticism of the model construction itself, and testing different formulation of the modeled relationships and variable combinations to identify models which are best fit for purpose. Tools such as Information Criterion, posterior predictive checks, Bayes factors, and other statistical diagnostics can inform the actuary about tradeoffs between different choices of model.</p>
</section>
<section id="paving-the-way-forward-for-actuaries" class="level2" data-number="10.10">
<h2 data-number="10.10" class="anchored" data-anchor-id="paving-the-way-forward-for-actuaries"><span class="header-section-number">10.10</span> Paving the Way Forward for Actuaries</h2>
<p>Bayesian approaches to statistical problems are rapidly changing the professional statistical field. To the extent that the actuarial profession incorporates statistical procedures we should consider adopting the same practices. The benefits of this are a better understanding of the distribution of risks, results that are more interpretable and explainable, and techniques that can be applied to a wider range of problems. The combination of these things would serve to enhance actuarial best practices related to understanding and communicating about risk.</p>
<p>For actuaries interested in learning more, there are number of available resources to be found. Textbooks recommended by the author are:</p>
<ul>
<li>Statistical Rethinking (McElreath)</li>
<li>Bayes Rules! (Johnson, Ott, Dogucu)</li>
<li>Bayesian Data Analysis (Gelman, et. al.)</li>
</ul>
<p>Additionally, the author has published a few examples of Bayesian analysis in an actuarial context on JuliaActuary.org.</p>
<section id="further-reading" class="level3" data-number="10.10.1">
<h3 data-number="10.10.1" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">10.10.1</span> Further Reading</h3>
<section id="section" class="level5" data-number="10.10.1.0.1">
<h5 data-number="10.10.1.0.1" class="anchored" data-anchor-id="section"><span class="header-section-number">10.10.1.0.1</span> </h5>
</section>
</section>
</section>
<section id="httpsdata.ca.govdatasetannual-precipitation-data-for-northern-california-1944-current" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> https://data.ca.gov/dataset/annual-precipitation-data-for-northern-california-1944-current</h1>
</section>
<section id="point-we-can-use-the-likelihood-component-of-bayes-rule-to-compare-models" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Point: we can use the likelihood component of bayes rule to compare models</h1>
</section>
<section id="three-models-are-compared-normal-lognormal-and-gamma-pearson-iii" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> three models are compared: normal, lognormal, and gamma (Pearson III)</h1>
</section>
<section id="httpsstats.stackexchange.comquestions55563estimating-parameters-of-log-pearson-iii-distribution-in-r" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> https://stats.stackexchange.com/questions/55563/estimating-parameters-of-log-pearson-iii-distribution-in-r</h1>
</section>
<section id="section-1" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> </h1>
<p>using CairoMakie using StatsBase using Distributions x = [39.51,42.65,44.09,41.92,28.42,58.65,30.18,64.4,29.02,37.00,32.17,36.37,47.55,27.71,58.26,36.55,49.57,39.84,82.22,47.58,51.18,32.28,52.48,65.24,51.12,25.03,23.27,26.11,47.3,31.8,61.45,94.95,34.8,49.53,28.65,35.3,34.8,27.45,20.7,36.99,60.54,22.5,64.85,43.1,37.55,82.05,27.9,36.55,28.7,29.25,42.32,31.93,41.8,55.9,20.65,29.28,18.4,39.31,20.36,22.73,12.75,23.35,29.59,44.47,20.06,46.48,13.46,9.34,16.51,48.24]</p>
<p>n = fit_mle(Normal, x) ln = fit_mle(LogNormal, x) c = 0.12 g = fit_mle(Gamma, log.(x.-c)) fig,ax,_ = density(x) plot!(ax,n) plot!(ax,ln) density!(ax,exp.(rand(g,10000) .+ c)) fig</p>
<p>search_params = [ (μ,σ) for μ in 0:0.5:100, σ in 1:0.1:20<br>
]</p>
<p>search = map(search_params) do (μ,σ) sum(log.(pdf.(Normal(μ,σ),x))) end m = argmax(search) search_params[m]</p>
<p>show(fig)</p>
<p>pdf(Normal(0,1),0.5)</p>
<p>sum((pdf.(ln,x)))/sum((pdf.(n,x))) sum((pdf.(g,log.(x.-c))))/sum((pdf.(n,x)))</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Log base two turns out to be the most natural representation of information content as it mimics the fundamental 0 or 1 value bit. A more complete introduction is available in “Information Theory, Inference, and Learning Algorithms” by David MacKay.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>A decision tree is a classification algorithm which attempts to optimally classify an output based on if/else type branches on the input variables.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><a href="https://www.researchgate.net/publication/239752412_Derivation_of_Probability_Distributions_for_Risk_Assessment" class="uri">https://www.researchgate.net/publication/239752412_Derivation_of_Probability_Distributions_for_Risk_Assessment</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Note that the approach discussed here is much more encompassing than the Bühlmann-Straub Bayesian approach described in the actuarial literature.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./software.html" class="pagination-link" aria-label="Applying Software Engineering Principles">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Applying Software Engineering Principles</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./computational-thinking.html" class="pagination-link" aria-label="Computational Thinking in an Actuarial and Financial Context">
        <span class="nav-page-text">Computational Thinking in an Actuarial and Financial Context</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>