name: "Feedback or Issue"
description: Share feedback, corrections, or ideas about the book.
title: "[Feedback] <short summary>"
labels:
  - needs-triage
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution!

        Contributor Notice (IP Waiver)
        By submitting content in this issue (including text, code, images, or files), you:
        - Represent that you have the right to share it; and
        - Grant the maintainers a perpetual, worldwide, irrevocable, royalty-free license to use, modify, reproduce, and distribute your contribution as part of this project and related materials; and
        - Waive and release any copyright, moral rights, or other intellectual property claims you may have in your submission to the fullest extent permitted by law.

        If you cannot agree to this, please do not submit the content here.
  - type: textarea
    id: description
    attributes:
      label: What would you like to report or suggest?
      placeholder: "Briefly describe the issue or suggestion."
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Where does this apply? (optional)
      placeholder: "Chapter/section/page or file path"
  - type: textarea
    id: extras
    attributes:
      label: Anything else? (optional)
      placeholder: "Links, screenshots, or context"

