on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download and Install Fonts
        run: |
          # Download the ZIP file
          curl -L -o fonts.zip https://github.com/cormullion/juliamono/releases/download/v0.053/JuliaMono.zip

          # Unzip the file
          unzip fonts.zip -d ./fonts

          # Install fonts (example for Linux)
          sudo cp ./fonts/*.ttf /usr/share/fonts/
          sudo fc-cache -fv

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true 

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      
      - name: Install Julia and Dependencies
        uses: julia-actions/setup-julia@v1
        with:
            version: '1'
      - name: Install dependencies
        run: julia -e 'import Pkg; Pkg.add("IJulia"); using IJulia' 
        
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
